openapi: 3.0.0
info:
  title: Tidal UI API Endpoints
  version: 1.0.0
  description: WORKING API endpoints used by the Tidal UI codebase - DO NOT use untested endpoints
servers:
  - url: '{baseUrl}'
    variables:
      baseUrl:
        default: https://triton.squid.wtf
        description: Base URL of the proxy API
paths:
  /track/:
    get:
      summary: Get track info and streaming URLs
      description: Primary endpoint for retrieving track information, manifest, and streaming URLs
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: integer
          description: Track ID
        - name: quality
          in: query
          schema:
            type: string
            enum: [LOSSLESS, HIGH, LOW, HI_RES_LOSSLESS]
            default: LOSSLESS
          description: Audio quality level
      responses:
        '200':
          description: Track lookup data with manifest and URLs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrackLookup'
  /album/:
    get:
      summary: Get album details and track listing
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: integer
          description: Album ID
      responses:
        '200':
          description: Album data with tracks
          content:
            application/json:
              schema:
                type: object
                properties:
                  album:
                    $ref: '#/components/schemas/Album'
                  tracks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Track'
  /artist/:
    get:
      summary: Get artist details and discography
      parameters:
        - name: f
          in: query
          required: true
          schema:
            type: integer
          description: Artist ID (using 'f' parameter)
      responses:
        '200':
          description: Artist details with albums and tracks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArtistDetails'
  /playlist/:
    get:
      summary: Get playlist details and items
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
          description: Playlist UUID
      responses:
        '200':
          description: Playlist data with track items
          content:
            application/json:
              schema:
                type: object
                properties:
                  playlist:
                    $ref: '#/components/schemas/Playlist'
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        item:
                          $ref: '#/components/schemas/Track'
  /search/:
    get:
      summary: Search across tracks, albums, artists, and playlists
      description: Unified search endpoint with different query parameters for different content types
      parameters:
        - name: s
          in: query
          schema:
            type: string
          description: Search tracks
        - name: al
          in: query
          schema:
            type: string
          description: Search albums
        - name: a
          in: query
          schema:
            type: string
          description: Search artists
        - name: p
          in: query
          schema:
            type: string
          description: Search playlists
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
  /lyrics/:
    get:
      summary: Get track lyrics
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: integer
          description: Track ID
      responses:
        '200':
          description: Lyrics data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lyrics'
  /covers:
    get:
      summary: Search for cover images
      parameters:
        - name: query
          in: query
          schema:
            type: string
          description: Search query for covers
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
          description: Maximum number of results
      responses:
        '200':
          description: Cover image search results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CoverImage'
  /dash/:
    get:
      summary: Get DASH manifest for high-resolution audio
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: integer
          description: Track ID
        - name: quality
          in: query
          schema:
            type: string
            enum: [HI_RES_LOSSLESS]
            default: HI_RES_LOSSLESS
          description: Audio quality (DASH specific)
      responses:
        '200':
          description: DASH manifest data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DashManifestResult'

components:
  schemas:
    TrackLookup:
      type: object
      properties:
        track:
          $ref: '#/components/schemas/Track'
        info:
          $ref: '#/components/schemas/TrackInfo'
        originalTrackUrl:
          type: string
          description: Direct stream URL if available
    Track:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        artists:
          type: array
          items:
            $ref: '#/components/schemas/Artist'
        album:
          $ref: '#/components/schemas/Album'
        duration:
          type: integer
        audioQuality:
          type: string
          enum: [LOSSLESS, HIGH, LOW, HI_RES_LOSSLESS]
    TrackInfo:
      type: object
      properties:
        trackId:
          type: integer
        audioMode:
          type: string
        audioQuality:
          type: string
        manifest:
          type: string
          description: Base64 encoded manifest
        manifestMimeType:
          type: string
        trackReplayGain:
          type: number
        albumReplayGain:
          type: number
        sampleRate:
          type: integer
        bitDepth:
          type: integer
    Album:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        artists:
          type: array
          items:
            $ref: '#/components/schemas/Artist'
        cover:
          type: string
        releaseDate:
          type: string
        numberOfTracks:
          type: integer
        numberOfVolumes:
          type: integer
    Artist:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        type:
          type: string
        artistTypes:
          type: array
          items:
            type: string
    ArtistDetails:
      allOf:
        - $ref: '#/components/schemas/Artist'
        - type: object
          properties:
            albums:
              type: array
              items:
                $ref: '#/components/schemas/Album'
            tracks:
              type: array
              items:
                $ref: '#/components/schemas/Track'
    Playlist:
      type: object
      properties:
        uuid:
          type: string
        title:
          type: string
        description:
          type: string
        duration:
          type: integer
        numberOfTracks:
          type: integer
        creator:
          $ref: '#/components/schemas/Artist'
        squareImage:
          type: string
        image:
          type: string
    SearchResponse:
      type: object
      properties:
        items:
          type: array
          description: Array of search results (tracks, albums, artists, or playlists)
        limit:
          type: integer
        offset:
          type: integer
        totalNumberOfItems:
          type: integer
    Lyrics:
      type: object
      properties:
        trackId:
          type: integer
        lyricsProvider:
          type: string
        providerLyricsId:
          type: string
        lyrics:
          type: string
        subtitles:
          type: string
    CoverImage:
      type: object
      description: Cover image metadata
    DashManifestResult:
      oneOf:
        - type: object
          properties:
            kind:
              type: string
              enum: [dash]
            manifest:
              type: string
            contentType:
              type: string
        - type: object
          properties:
            kind:
              type: string
              enum: [flac]
            manifestText:
              type: string
            urls:
              type: array
              items:
                type: string
            contentType:
              type: string
